#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
scrape_iq_questions.py  —  PASSIVE MODE
────────────────────────────────────────
Opens a browser at test.iqtestacademy.org.
YOU navigate through the test manually (click each answer or Skip).
The script watches for page changes and automatically saves every question image.

Usage
─────
  python scrape_iq_questions.py            ← opens browser, you navigate
  python scrape_iq_questions.py --finalize ← regenerates JS from edited JSON

After the test
──────────────
  1. Open  scraped_questions_raw.json
  2. Set   "answer": <0-based index>  for each question  (0=A, 1=B, 2=C …)
  3. Run   python scrape_iq_questions.py --finalize
"""

import asyncio, base64, hashlib, json, re, sys, urllib.parse, urllib.request
from pathlib import Path
from playwright.async_api import async_playwright

# ── fix Windows console encoding ─────────────────────────────────────────────
if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

# ── paths ─────────────────────────────────────────────────────────────────────
IMG_DIR  = Path("frontend/static/images/iq_scraped")
RAW_JSON = Path("scraped_questions_raw.json")
BANK_JS  = Path("frontend/static/iq_question_bank.js")
IMG_DIR.mkdir(parents=True, exist_ok=True)

# ── image saving ──────────────────────────────────────────────────────────────

def save_image(src: str, stem: str) -> str | None:
    """Save image (data-URI or http URL) → returns local web path or None."""
    # Determine extension
    if src.startswith("data:"):
        mime = src.split(";")[0].split(":")[1] if ";" in src else src.split(",")[0].split(":")[1]
        ext  = {"image/svg+xml":".svg","image/png":".png","image/jpeg":".jpg",
                "image/gif":".gif","image/webp":".webp"}.get(mime, ".svg")
    else:
        ext = next((e for e in (".svg",".png",".jpg",".jpeg",".webp")
                    if src.lower().split("?")[0].endswith(e)), ".svg")

    fname = f"{stem}{ext}"
    dest  = IMG_DIR / fname
    if dest.exists():
        return f"/static/images/iq_scraped/{fname}"

    try:
        if src.startswith("data:"):
            header, payload = src.split(",", 1)
            if "base64" in header:
                dest.write_bytes(base64.b64decode(payload))
            else:
                dest.write_text(urllib.parse.unquote(payload), encoding="utf-8")
        else:
            req = urllib.request.Request(src, headers={"User-Agent":"Mozilla/5.0"})
            with urllib.request.urlopen(req, timeout=15) as r:
                dest.write_bytes(r.read())
        print(f"  [saved] {fname}", flush=True)
        return f"/static/images/iq_scraped/{fname}"
    except Exception as e:
        print(f"  [FAIL]  {fname}: {e}", flush=True)
        return None

# ── DOM extraction JS ─────────────────────────────────────────────────────────

IMAGES_JS = r"""
(function(){
  var out=[];
  var seen=new Set();
  function add(src,r){
    if(!src||seen.has(src)) return;
    seen.add(src);
    var isCDN = src.indexOf('cdn.bubble.io')>-1 || src.startsWith('http');
    out.push({src:src,
              w:Math.round(r.width),h:Math.round(r.height),
              area:Math.round(r.width*r.height),
              top:Math.round(r.top),
              isCDN: isCDN});
  }
  document.querySelectorAll('img').forEach(function(img){
    if(!img.src||img.src===location.href) return;
    var r=img.getBoundingClientRect();
    if(r.width<30||r.height<30) return;
    add(img.src, r);
  });
  return out;
})()
"""

QNUM_JS = """
(function(){
  var m=(document.body.innerText||'').match(/(\\d+)\\s*\\/\\s*(\\d+)/);
  return m?{cur:parseInt(m[1]),total:parseInt(m[2])}:null;
})()
"""

TITLE_JS = """
(function(){
  var skip=['being prepared','terms of use','privacy policy',
            'start the test','skip questions','growing difficulty'];
  var texts=[];
  document.querySelectorAll('p,h1,h2,h3,h4,span').forEach(function(el){
    var t=(el.innerText||'').trim();
    if(t.length<10||t.length>300) return;
    if(skip.some(function(s){return t.toLowerCase().includes(s);})) return;
    texts.push(t);
  });
  // prefer text with a question mark
  var q=texts.find(function(t){return t.includes('?');});
  return q||texts[0]||'Which image completes the pattern?';
})()
"""

# ── fingerprint ───────────────────────────────────────────────────────────────

def fingerprint(imgs):
    return tuple(sorted(
        hashlib.md5(i["src"].encode("utf-8","replace")).hexdigest()
        for i in imgs
    ))

# ── question bank writer ──────────────────────────────────────────────────────

JS_HEADER = """\
// =============================================================================
// IQ Question Bank  v2.0  —  generated by scrape_iq_questions.py
// =============================================================================
// STANDALONE — drop this file + /static/images/iq_scraped/ into any project.
// The rendering engine (iq_assessment.js) reads window.IQ_QUESTION_BANK.
//
// Schema per question
// ───────────────────
//   id      : string          unique key  (e.g. "q01")
//   title   : string          prompt shown to the candidate
//   source  : string          category badge
//   imgUrl  : string | null   main question image  (/static/images/iq_scraped/…)
//   imgOpts : string[] | null image answer options (local paths)
//   opts    : string[] | null text answer options
//   answer  : number          0-based index of the correct option
//   time    : number          seconds per question
//   exp     : string          explanation revealed after answering
//
// To change question set: replace this file only. Never touch iq_assessment.js.
// =============================================================================

/* global IQ_QUESTION_BANK */
var IQ_QUESTION_BANK = [
"""

INTERNAL = {"_screenshot","_all_texts","_n_imgs"}

def write_bank(questions):
    entries = []
    for q in questions:
        obj = {k:v for k,v in q.items() if k not in INTERNAL}
        entries.append("  " + json.dumps(obj, ensure_ascii=False))
    BANK_JS.write_text(JS_HEADER + ",\n".join(entries) + "\n];\n", encoding="utf-8")

# ── main ──────────────────────────────────────────────────────────────────────

async def run():
    questions = []
    saved_fps = set()   # fingerprints already captured
    last_qnum = 0

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False, slow_mo=100)
        ctx     = await browser.new_context(viewport={"width":1280,"height":900},
                    user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36")
        page    = await ctx.new_page()

        print("\n Opening https://test.iqtestacademy.org/ ...", flush=True)
        await page.goto("https://test.iqtestacademy.org/", wait_until="networkidle")
        await page.wait_for_timeout(2000)

        print("""
╔══════════════════════════════════════════════════════════════╗
║   PASSIVE SCRAPER — browser is open, YOU navigate           ║
║                                                             ║
║   1. Click  Start  in the browser                           ║
║   2. For each question, look at it, then click  Skip        ║
║      (or click the correct answer if you know it)           ║
║   3. After all 20 questions, close the browser              ║
║                                                             ║
║   The script saves images automatically in the background.  ║
╚══════════════════════════════════════════════════════════════╝
""", flush=True)

        # Track URLs that appear on EVERY question — those are permanent UI chrome
        permanent_urls: set = set()
        prev_urls:      set = set()
        last_qnum_seen      = 0

        # Poll for page changes every second until browser closes
        while True:
            try:
                await page.wait_for_timeout(900)
            except Exception:
                break   # browser was closed

            try:
                imgs  = await page.evaluate(IMAGES_JS)
                qinfo = await page.evaluate(QNUM_JS)
            except Exception:
                break   # browser closed mid-poll

            if not imgs or not qinfo:
                continue

            cur   = qinfo["cur"]
            total = qinfo["total"]
            fp    = fingerprint(imgs)

            # Already captured this exact page state
            if fp in saved_fps:
                continue

            # When question number advances, URLs shared with previous page = chrome
            current_urls = set(i["src"] for i in imgs)
            if cur != last_qnum_seen and last_qnum_seen > 0:
                shared = prev_urls & current_urls
                permanent_urls.update(shared)
            last_qnum_seen = cur
            prev_urls      = current_urls
            saved_fps.add(fp)

            print(f"\n[Q{cur}/{total}] New question detected — saving images ...", flush=True)

            # Screenshot
            ss = f"_q{cur:02d}_screen.png"
            try:
                await page.screenshot(path=str(IMG_DIR / ss))
            except Exception:
                pass

            # ── Classify images ───────────────────────────────────────────────
            # Remove permanent background/chrome images from consideration
            fresh = [i for i in imgs if i["src"] not in permanent_urls]

            cdn_fresh  = sorted([i for i in fresh if i.get("isCDN")],      key=lambda x: x["top"])
            data_fresh = sorted([i for i in fresh if not i.get("isCDN")],   key=lambda x: x["top"])

            main_src, opt_srcs = None, []

            if cdn_fresh:
                main_src = cdn_fresh[0]["src"]
                opt_srcs = [i["src"] for i in cdn_fresh[1:8]]
            elif data_fresh:
                main_src = data_fresh[0]["src"]
                opt_srcs = [i["src"] for i in data_fresh[1:8]]
            elif imgs:
                # Fallback before chrome is identified (Q1)
                all_s = sorted(imgs, key=lambda x: x["top"])
                main_src = all_s[0]["src"]
                opt_srcs = [i["src"] for i in all_s[1:8]]

            # Deduplicate options
            opt_srcs = list(dict.fromkeys(opt_srcs))

            # Save
            main_local = save_image(main_src, f"q{cur:02d}_main") if main_src else None
            opt_locals = []
            for idx, src in enumerate(opt_srcs):
                loc = save_image(src, f"q{cur:02d}_opt_{'abcdefgh'[idx]}")
                if loc:
                    opt_locals.append(loc)

            # Title
            try:
                title = await page.evaluate(TITLE_JS)
            except Exception:
                title = "Which image completes the pattern?"

            record = {
                "id":      f"q{cur:02d}",
                "title":   title,
                "source":  "IQ Test Academy",
                "imgUrl":  main_local,
                "imgOpts": opt_locals if opt_locals else None,
                "opts":    None,
                "answer":  None,   # fill in after reviewing screenshots
                "time":    90,
                "exp":     "",
                "_screenshot": ss,
                "_n_imgs": len(imgs),
            }

            # Replace or append (handle revisiting a question)
            existing = next((i for i,q in enumerate(questions) if q["id"]==record["id"]), None)
            if existing is not None:
                questions[existing] = record
            else:
                questions.append(record)

            # Sort by id and save progress after every question
            questions.sort(key=lambda q: q["id"])
            RAW_JSON.write_text(json.dumps(questions, indent=2, ensure_ascii=False), encoding="utf-8")
            write_bank(questions)
            print(f"  Saved Q{cur}  ({len(questions)}/{total} done)  — "
                  f"main={main_local}  opts={len(opt_locals)}", flush=True)

            last_qnum = cur
            if last_qnum >= total:
                print(f"\n All {total} questions captured!", flush=True)

        await browser.close()

    questions.sort(key=lambda q: q["id"])
    RAW_JSON.write_text(json.dumps(questions, indent=2, ensure_ascii=False), encoding="utf-8")
    write_bank(questions)

    print(f"\n Done — {len(questions)} questions saved.", flush=True)
    print("=" * 60, flush=True)
    null_ans = [q["id"] for q in questions if q["answer"] is None]
    if null_ans:
        print(f" Still need answers for: {null_ans}", flush=True)
        print(f" → Open scraped_questions_raw.json", flush=True)
        print(f" → Set \"answer\": 0-4 for each (0=A, 1=B, 2=C, 3=D, 4=E)", flush=True)
        print(f" → Run:  python scrape_iq_questions.py --finalize", flush=True)
    print("=" * 60, flush=True)


# ── finalize ──────────────────────────────────────────────────────────────────

def finalize():
    if not RAW_JSON.exists():
        print(f"[error] {RAW_JSON} not found. Run without --finalize first.")
        sys.exit(1)
    qs = json.loads(RAW_JSON.read_text(encoding="utf-8"))
    null_ans = [q["id"] for q in qs if q.get("answer") is None]
    if null_ans:
        print(f"[warn] {len(null_ans)} questions still have answer=null: {null_ans}")
    write_bank(qs)
    print(f"[done] {BANK_JS} regenerated  ({len(qs)} questions)")


if __name__ == "__main__":
    if "--finalize" in sys.argv:
        finalize()
    else:
        asyncio.run(run())
